-- liquibase formatted sql
-- changeset milosz08:aq6

CREATE TABLE IF NOT EXISTS equipment_types
(
    id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX (id, name)
)
ENGINE=InnoDB COLLATE=utf16_polish_ci;


CREATE TABLE IF NOT EXISTS equipment_brands
(
    id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX (id, name)
)
ENGINE=InnoDB COLLATE=utf16_polish_ci;


CREATE TABLE IF NOT EXISTS equipment_colors
(
    id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX (id, name)
)
ENGINE=InnoDB COLLATE=utf16_polish_ci;


CREATE TABLE IF NOT EXISTS account_units
(
    id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX (id, name)
)
    ENGINE=InnoDB COLLATE=utf16_polish_ci;
