name: Build, create Docker image and send to Dockerhub

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/docker-image.yml"
      - "gradle/**"
      - "src/**"
      - "build.gradle"
      - "Dockerfile.pipeline"
      - "settings.gradle"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
          check-latest: false

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Clean build dir
        run: ./gradlew clean --no-daemon

      - name: Package to WAR
        run: ./gradlew war --no-daemon

      - name: Upload generated WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-war
          path: build/libs/ROOT.war
          retention-days: 1

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download generated JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: output-war
          path: ${{ github.workspace }}/docker

      - name: Set up builder
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.pipeline
          push: true
          tags: milosz08/ski-rental-service-app:latest

      - name: Logout from Docker Hub
        run: docker logout
